### ISSUE TITLE
TypeError: Cannot read property '0' of undefined angular.js:10126

### ISSUE THREAD

**Issue by Langting** [soton-ecs-2014-gdp-12/authoring-tool#28]
When I setup, and the video cannot play. 
**ERROR**

 `Uncaught SyntaxError: Unexpected token <`  `(index):1`  

When I play the video, the **ERROR** occurs,
`
TypeError: Cannot read property '0' of undefined
    at playPause (http://localhost:5002/app/bower_components/videogular/videogular.min.js:1:3237)
    at Scope.onClickPlayPause (http://localhost:5002/app/bower_components/videogular-controls/controls.js:127:10)
    at Parser.functionCall (http://localhost:5002/app/bower_components/angular/angular.js:10903:21)
    at ngEventDirectives.(anonymous function).compile.element.on.callback (http://localhost:5002/app/bower_components/angular/angular.js:19259:17)
    at Scope.$get.Scope.$eval (http://localhost:5002/app/bower_components/angular/angular.js:12811:28)
    at Scope.$get.Scope.$apply (http://localhost:5002/app/bower_components/angular/angular.js:12909:23)
    at HTMLButtonElement.<anonymous> (http://localhost:5002/app/bower_components/angular/angular.js:19264:23)
    at http://localhost:5002/app/bower_components/angular/angular.js:2853:10
    at forEach (http://localhost:5002/app/bower_components/angular/angular.js:325:18)
    at HTMLButtonElement.eventHandler (http://localhost:5002/app/bower_components/angular/angular.js:2852:5)`

**Comment by chewett** [comment]
This looks like a similar/the same error you reported here: https://github.com/angular/angular.js/issues/12380

Similarly, unless you can provide more information we are likely unable to help ourselves.

**Comment by Langting** [comment]
Yes, but it just shows likes this and I haven't change the code. Is anything I should take care when set up the authoring-tool?

**Comment by chewett** [comment]
I will set up an instance in a minute and see what happens.

**Comment by chewett** [comment]
By following the readme, you can easily setup the authoring tool. I have downloaded the repo and ran `npm install` which has installed the necessary dependencies. Running `npm start` allows me to access and run the video normally.

Therefore unless you find a bug with the authoring tool or provide more information I see no problem here.

**Comment by Langting** [comment]
When I ran bower install, there are some versions I need to select. Is there any problems occurring due to the version?

```
Please note that,
    videogular-controls#0.6.3, videogular-themes-default#0.6.3 depends on videogular#* which resolved to videogular#0.6.3
    authoring-tool depends on videogular#~0.6.1 which resolved to videogular#0.6.3
    videogular-controls#1.2.4 depends on videogular#1.2.4 which resolved to videogular#1.2.4
Resort to using videogular#~0.6.1 which resolved to videogular#0.6.3
Code incompatibilities may occur.


Please note that,
    angular-loader#1.2.28, angular-mocks#1.2.28, angular-route#1.2.28, angular-sanitize#1.2.28 depends on angular#1.2.28 which resolved to angular#1.2.28
    authoring-tool depends on angular#1.2.x which resolved to angular#1.2.28
    angular-bootstrap#0.12.1 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.28
    videogular#0.6.3 depends on angular#~1.2.0 which resolved to angular#1.2.28
    angular-charts#0.2.7 depends on angular#* which resolved to angular#1.2.28
    videogular#1.2.4 depends on angular#~1.3.x which resolved to angular#1.3.17
    angular-sanitize#1.3.17 depends on angular#1.3.17 which resolved to angular#1.3.17
Resort to using angular#1.2.28 which resolved to angular#1.2.28
Code incompatibilities may occur.


Please note that,
    authoring-tool depends on videogular-controls#~0.6.1 which resolved to videogular-controls#0.6.3
    videogular-cuepoints depends on videogular-controls#1.x which resolved to videogular-controls#1.2.4
Resort to using videogular-controls#~0.6.1 which resolved to videogular-controls#0.6.3
Code incompatibilities may occur.


Please note that,
    videogular#0.6.3 depends on angular-sanitize#~1.2.0 which resolved to angular-sanitize#1.2.28
    videogular#1.2.4 depends on angular-sanitize#~1.3.x which resolved to angular-sanitize#1.3.17
Resort to using angular-sanitize#~1.2.0 which resolved to angular-sanitize#1.2.28
Code incompatibilities may occur.

```
